import { AlertCircle, AlignJustify, ArrowDownToLine, Braces, Check, ChevronRight, Code2, Columns2, ExternalLink, FileCode2, GitMerge, ListTree, ScrollText, ShieldCheck, Square, TerminalSquare, TestTube2, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { openPath } from "@tauri-apps/plugin-opener";
import type { DetailTab, LiveLog, RunDetail } from "../types";
import { duration, shortId, titleCase } from "../lib/format";
import { StatusBadge, StatusIcon } from "./Status";

interface Props {run:RunDetail;diff:string;liveLogs:LiveLog[];onStop:()=>void;onApply:()=>void;onDiscard:()=>void;onError:(message:string)=>void;busyAction?:string}
const tabs:{id:DetailTab;label:string;icon:typeof ListTree}[]=[{id:"summary",label:"Summary",icon:ListTree},{id:"activity",label:"Activity",icon:ChevronRight},{id:"files",label:"Files",icon:FileCode2},{id:"diff",label:"Diff",icon:Code2},{id:"tests",label:"Tests",icon:TestTube2},{id:"review",label:"Review",icon:ShieldCheck},{id:"logs",label:"Logs",icon:TerminalSquare}];

export function RunWorkspace({run,diff,liveLogs,onStop,onApply,onDiscard,onError,busyAction}:Props){
  const [tab,setTab]=useState<DetailTab>("summary"); const active=["running","queued"].includes(run.status);
  return <main className="run-page">
    <header className="topbar run-header"><div><div className="run-kicker"><span>RUN #{shortId(run.id)}</span><StatusBadge status={run.status}/></div><h1>{run.task}</h1><p>{run.projectName} · {run.discardedAt?"Worktree discarded":run.worktreePath?"Isolated worktree":"Preparing worktree"}</p></div><div className="header-actions">
      {run.worktreePath&&<button className="secondary-button" onClick={()=>openPath(run.worktreePath!).catch(error=>onError(String(error)))}><ExternalLink size={14}/> Open worktree</button>}
      {active?<button className="danger-button" onClick={onStop}><Square size={13} fill="currentColor"/> Stop run</button>:run.appliedAt?<button className="secondary-button" disabled><Check size={14}/> Applied</button>:run.worktreePath&&run.status==="completed"?<button className="primary-button compact" disabled={!!busyAction} onClick={onApply}><GitMerge size={15}/>{busyAction==="apply"?"Applying…":"Apply changes"}</button>:null}
    </div></header>
    <div className="tabs" role="tablist" aria-label="Run details">{tabs.map(item=><button role="tab" aria-selected={tab===item.id} key={item.id} className={tab===item.id?"active":""} onClick={()=>setTab(item.id)}><item.icon size={14}/>{item.label}{item.id==="files"&&run.changedFiles.length>0?<span>{run.changedFiles.length}</span>:null}</button>)}</div>
    <section className="run-content" role="tabpanel">
      {tab==="summary"&&<Summary run={run}/>} {tab==="activity"&&<Activity run={run} liveLogs={liveLogs}/>} {tab==="files"&&<Files run={run}/>} {tab==="diff"&&<DiffView diff={diff}/>} {tab==="tests"&&<Tests run={run}/>} {tab==="review"&&<Review run={run}/>} {tab==="logs"&&<Logs run={run} liveLogs={liveLogs}/>} 
    </section>
    {!active&&run.worktreePath&&<footer className="run-footer"><span>{run.appliedAt?"Changes were applied; this isolated worktree is retained for inspection.":"Changes remain isolated until you explicitly apply them."}</span><button className="text-danger" disabled={!!busyAction} onClick={onDiscard}><Trash2 size={13}/>Discard worktree</button></footer>}
  </main>
}

function Summary({run}:{run:RunDetail}){
  const stages=stageTimeline(run); const passed=run.verification.filter(v=>v.success).length; const failed=run.verification.filter(v=>!v.success).length;
  return <div className="summary-grid"><div className="panel timeline-panel"><div className="panel-heading"><div><span className="eyebrow">WORKFLOW</span><h2>Run timeline</h2></div><span>{stages.filter(s=>s.status==="completed").length} / {stages.length} stages</span></div><div className="timeline">{stages.map((stage,index)=><div className={`timeline-item ${stage.status}`} key={stage.key}><div className="timeline-rail"><StatusIcon status={stage.status}/>{index<stages.length-1&&<i/>}</div><div className="timeline-body"><header><div><strong>{stage.label}</strong><span className={`agent-tag ${stage.agent.toLowerCase()}`}>{stage.agent}</span></div><small>{stage.duration}</small></header><p>{stage.summary}</p></div></div>)}</div></div>
    <aside className="summary-side"><div className={`result-card ${run.status}`}><span className="eyebrow">DUET RESULT</span><div className="result-title"><StatusIcon status={run.status} size={19}/><h2>{resultTitle(run.status)}</h2></div><p>{resultCopy(run)}</p></div>
      <div className="metrics-card"><div><span>Files changed</span><strong>{run.changedFiles.length}</strong></div><div><span>Lines</span><strong className="changes"><b>+{run.additions}</b><em>−{run.deletions}</em></strong></div><div><span>Checks</span><strong>{passed} passed{failed?` · ${failed} failed`:""}</strong></div></div>
      {run.architecture&&<div className="mini-card"><Braces size={15}/><div><strong>Architecture plan</strong><p>Saved with this run and provided to the builder.</p></div></div>}
    </aside></div>
}

function Activity({run,liveLogs}:{run:RunDetail;liveLogs:LiveLog[]}){const entries=[...run.stages.map(s=>({time:s.startedAt,text:`${s.agent} started ${titleCase(s.kind)}`,status:s.status})),...liveLogs.slice(-30).map(log=>({time:log.receivedAt,text:log.text,status:"running"}))].sort((a,b)=>a.time.localeCompare(b.time));return <div className="panel wide-panel"><div className="panel-heading"><div><span className="eyebrow">EVENTS</span><h2>Activity stream</h2></div></div><div className="activity-list">{entries.length?entries.map((e,i)=><div key={`${e.time}-${i}`}><time>{new Date(e.time).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:"2-digit"})}</time><StatusIcon status={e.status}/><span>{e.text}</span></div>):<Empty icon={ScrollText} title="No activity yet" copy="Events will appear as the workflow runs."/>}</div></div>}
function Files({run}:{run:RunDetail}){return <div className="panel wide-panel"><div className="panel-heading"><div><span className="eyebrow">GIT</span><h2>Changed files</h2></div><span className="changes"><b>+{run.additions}</b><em>−{run.deletions}</em></span></div>{run.changedFiles.length?<div className="file-list">{run.changedFiles.map(file=><div key={file.path}><span className={`file-status ${file.status}`}>{file.status[0].toUpperCase()}</span><code>{file.path}</code><span className="changes"><b>+{file.additions}</b><em>−{file.deletions}</em></span></div>)}</div>:<Empty icon={FileCode2} title="No changed files" copy="Changed files appear after the implementation stage."/>}</div>}
function DiffView({diff}:{diff:string}){const [mode,setMode]=useState<"unified"|"split">("split");const allLines=diff.split("\n");const lines=allLines.slice(0,5000);const split=useMemo(()=>parseSplitDiff(lines.join("\n")),[diff]);return <div className="diff-panel"><div className="diff-toolbar"><span><Code2 size={14}/> {mode==="split"?"Split diff":"Unified diff"}</span><div className="diff-toolbar-actions"><small>{allLines.length.toLocaleString()} lines{allLines.length>lines.length?" · preview capped":""}</small><div role="group" aria-label="Diff layout"><button className={mode==="split"?"active":""} aria-label="Split diff" onClick={()=>setMode("split")}><Columns2 size={13}/></button><button className={mode==="unified"?"active":""} aria-label="Unified diff" onClick={()=>setMode("unified")}><AlignJustify size={13}/></button></div></div></div>{diff?(mode==="unified"?<pre className="diff-code">{lines.map((line,i)=><div key={i} className={line.startsWith("+")&&!line.startsWith("+++")?"added":line.startsWith("-")&&!line.startsWith("---")?"removed":line.startsWith("@@")?"hunk":line.startsWith("diff ")?"file":""}><span>{i+1}</span><code>{line||" "}</code></div>)}</pre>:<div className="split-diff">{split.map((row,index)=><div key={index} className={`split-row ${row.kind}`}><span>{row.oldNumber??""}</span><code>{row.oldText??" "}</code><span>{row.newNumber??""}</span><code>{row.newText??" "}</code></div>)}</div>):<Empty icon={Code2} title="No diff available" copy="The implementation has not changed files yet."/>}</div>}

interface SplitRow {oldNumber?:number;newNumber?:number;oldText?:string;newText?:string;kind:"context"|"changed"|"added"|"removed"|"meta"}
export function parseSplitDiff(diff:string):SplitRow[]{const lines=diff.split("\n");const rows:SplitRow[]=[];let oldNumber=0,newNumber=0;for(let index=0;index<lines.length;){const line=lines[index];if(line.startsWith("@@")){const match=line.match(/^@@ -(\d+)(?:,\d+)? \+(\d+)(?:,\d+)? @@/);if(match){oldNumber=Number(match[1]);newNumber=Number(match[2])}rows.push({oldText:line,newText:line,kind:"meta"});index++;continue}if(line.startsWith("-")&&!line.startsWith("---")){const removed:string[]=[];const added:string[]=[];while(index<lines.length&&lines[index].startsWith("-")&&!lines[index].startsWith("---"))removed.push(lines[index++].slice(1));while(index<lines.length&&lines[index].startsWith("+")&&!lines[index].startsWith("+++"))added.push(lines[index++].slice(1));for(let offset=0;offset<Math.max(removed.length,added.length);offset++){const oldText=removed[offset],newText=added[offset];rows.push({oldNumber:oldText!==undefined?oldNumber++:undefined,newNumber:newText!==undefined?newNumber++:undefined,oldText,newText,kind:oldText!==undefined&&newText!==undefined?"changed":oldText!==undefined?"removed":"added"})}continue}if(line.startsWith("+")&&!line.startsWith("+++")){rows.push({newNumber:newNumber++,newText:line.slice(1),kind:"added"});index++;continue}if(line.startsWith(" ")){rows.push({oldNumber:oldNumber++,newNumber:newNumber++,oldText:line.slice(1),newText:line.slice(1),kind:"context"});index++;continue}rows.push({oldText:line,newText:line,kind:"meta"});index++}return rows}
function Tests({run}:{run:RunDetail}){return <div className="checks-stack">{run.verification.length?run.verification.map((check,i)=><details className={`check-card ${check.success?"pass":"fail"}`} key={`${check.name}-${i}`} open={!check.success}><summary><StatusIcon status={check.success?"passed":"failed"}/><div><strong>{check.name}</strong><code>{check.command}</code></div><span>{duration(check.durationMs)} · exit {check.exitCode??"—"}</span><ArrowDownToLine size={14}/></summary><pre>{check.stdout}{check.stderr&&`\n${check.stderr}`}</pre></details>):<Empty icon={TestTube2} title="Verification has not run" copy="Duet—not an agent—will execute the configured checks."/>}</div>}
function Review({run}:{run:RunDetail}){const parsed=useMemo(()=>{try{return run.review?JSON.parse(run.review):null}catch{return null}},[run.review]);if(!parsed)return <Empty icon={ShieldCheck} title="Review is waiting" copy="Codex reviews the actual diff after objective verification."/>;return <div className="review-layout"><div className={`review-verdict ${parsed.verdict}`}><StatusIcon status={parsed.verdict}/><div><span className="eyebrow">CODEX REVIEW</span><h2>{String(parsed.verdict).toUpperCase()}</h2><p>{parsed.summary}</p></div></div><div className="issue-list">{parsed.issues?.length?parsed.issues.map((issue:any,i:number)=><div className="issue-card" key={i}><header><span className={`severity ${issue.severity}`}>{issue.severity}</span><strong>{issue.category}</strong>{issue.file&&<code>{issue.file}{issue.line?`:${issue.line}`:""}</code>}</header><h3>{issue.problem}</h3><p>{issue.reason}</p><div><AlertCircle size={14}/><span>{issue.suggestedFix||issue.suggested_fix}</span></div></div>):<div className="all-clear"><ShieldCheck/><strong>No material issues found</strong><p>Codex approved the implementation after reviewing the diff and verification output.</p></div>}</div></div>}
function Logs({run,liveLogs}:{run:RunDetail;liveLogs:LiveLog[]}){const persisted=run.stages.flatMap(s=>s.rawOutput?[`\n── ${s.agent} / ${s.kind} ──`,s.rawOutput]:[]);return <div className="terminal"><div className="terminal-head"><span/><span/><span/><strong>Duet raw output</strong></div><pre>{[...persisted,...liveLogs.map(log=>log.text)].join("\n")||"Waiting for agent output…"}</pre></div>}
function Empty({icon:Icon,title,copy}:{icon:typeof Code2;title:string;copy:string}){return <div className="empty-panel"><Icon/><strong>{title}</strong><p>{copy}</p></div>}

function stageTimeline(run:RunDetail){const expected=[{key:"architect",label:"Architecture",agent:"Codex"},{key:"build",label:"Implementation",agent:"Claude"},{key:"verify",label:"Objective verification",agent:"Duet"},{key:"review",label:"Adversarial review",agent:"Codex"}];const repairs=run.stages.filter(s=>s.kind.startsWith("repair")).map((s,i)=>({key:s.kind,label:`Repair round ${i+1}`,agent:"Claude"}));return [...expected,...repairs].map(e=>{const records=run.stages.filter(s=>s.kind===e.key);const s=records[records.length-1];let status=s?.status||"pending";if(!s&&run.currentStage===e.key)status="running";return {...e,status,summary:s?.summary||(status==="pending"?"Waiting for dependencies":"Working…"),duration:duration(s?.durationMs)}})}
function resultTitle(status:string){return status==="completed"?"Verified":status==="failed"?"Could not complete":status==="interrupted"?"Interrupted":status==="cancelled"?"Stopped":"In progress"}
function resultCopy(run:RunDetail){if(run.status==="completed")return run.appliedAt?"Verified changes were explicitly applied to the original working tree.":"Objective checks passed and Codex approved the implementation.";if(run.status==="failed")return run.error||"Inspect the failed checks or unresolved review findings before continuing.";if(run.status==="interrupted")return run.error||"Duet closed while this run was active. Its worktree is preserved for inspection.";if(run.status==="cancelled")return "The run was stopped by the user. Its isolated worktree is preserved.";return `Duet is currently in the ${titleCase(run.currentStage)} stage.`}
