import { Check, ChevronLeft, CircleHelp, Command, Database, GitBranch, HardDrive, KeyRound, RefreshCw, ShieldCheck, X } from "lucide-react";
import { useEffect, useState } from "react";
import type { DoctorReport, ToolStatus } from "../types";
import { api, errorMessage } from "../lib/api";

export function Settings({onBack}:{onBack:()=>void}){const [report,setReport]=useState<DoctorReport>();const [error,setError]=useState("");const [loading,setLoading]=useState(true);const load=()=>{setLoading(true);setError("");api.doctor().then(setReport).catch(e=>setError(errorMessage(e))).finally(()=>setLoading(false))};useEffect(load,[]);
  return <main className="settings-page"><header className="topbar"><div><button className="back-button" onClick={onBack}><ChevronLeft size={15}/>Workspace</button><h1>Settings & Doctor</h1></div><button className="secondary-button" onClick={load} disabled={loading}><RefreshCw size={14} className={loading?"spin":""}/> Run diagnostics</button></header>
    <div className="settings-content"><section><span className="eyebrow">AGENTS</span><h2>Local coding agents</h2><p className="section-copy">Duet delegates to the official CLIs already authenticated on this Mac. It never asks for or stores API keys.</p><div className="doctor-grid"><ToolCard name="Claude Code" initials="CL" status={report?.claude} loading={loading}/><ToolCard name="OpenAI Codex" initials="CX" status={report?.codex} loading={loading}/></div></section>
      <section><span className="eyebrow">SYSTEM</span><h2>Runtime diagnostics</h2><div className="system-list"><SystemRow icon={GitBranch} label="Git" value={report?.git.version||"Checking…"} ok={report?.git.installed}/><SystemRow icon={Database} label="Local database" value={report?.databaseHealthy?"SQLite is healthy":"Database check failed"} ok={report?.databaseHealthy}/><SystemRow icon={HardDrive} label="Application data" value={report?.appDataWritable?"Writable":"Not writable"} ok={report?.appDataWritable}/><SystemRow icon={Command} label="Platform" value={report?.os||"Checking…"} ok={!!report}/></div></section>
      <section className="privacy-card"><ShieldCheck/><div><h3>Local-first by design</h3><p>Duet sends no source code, prompts, logs, or agent output to a Duet cloud service. Network behavior belongs only to the official Claude and Codex CLIs you run.</p></div></section>
      {error&&<div className="error-banner"><CircleHelp size={16}/>{error}</div>}
    </div></main>}

function ToolCard({name,initials,status,loading}:{name:string;initials:string;status?:ToolStatus;loading:boolean}){return <article className="tool-card"><div className={`tool-logo ${initials.toLowerCase()}`}>{initials}</div><div className="tool-info"><header><h3>{name}</h3>{loading?<span className="skeleton short"/>:<span className={`availability ${status?.installed?"ok":"bad"}`}>{status?.installed?<><Check size={12}/>Installed</>:<><X size={12}/>Missing</>}</span>}</header><dl><div><dt>Path</dt><dd>{status?.path||"Not detected"}</dd></div><div><dt>Version</dt><dd>{status?.version||"—"}</dd></div><div><dt>Authentication</dt><dd>{status?.authenticated===true?<span className="good"><KeyRound size={12}/>Authenticated</span>:status?.authenticated===false?<span className="warn">Login required or not detectable</span>:"Not detectable"}</dd></div></dl><p>{status?.detail}</p></div></article>}
function SystemRow({icon:Icon,label,value,ok}:{icon:typeof GitBranch;label:string;value:string;ok?:boolean}){return <div><span className="system-icon"><Icon size={16}/></span><strong>{label}</strong><code>{value}</code><span className={`check-dot ${ok?"ok":""}`}>{ok&&<Check size={11}/>}</span></div>}
