import { Check, ChevronLeft, CircleHelp, Command, Database, GitBranch, HardDrive, KeyRound, LogIn, RefreshCw, ShieldCheck, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import type { AppPreferences, DoctorReport, ToolStatus } from "../types";
import { api, errorMessage } from "../lib/api";

export function Settings({onBack}:{onBack:()=>void}){const [report,setReport]=useState<DoctorReport>();const [preferences,setPreferences]=useState<AppPreferences>({editor:"auto",maxRepairs:3});const [error,setError]=useState("");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [saved,setSaved]=useState(false);const [authenticating,setAuthenticating]=useState(false);const cancelled=useRef(false);const load=()=>{setLoading(true);setError("");Promise.all([api.doctor(),api.getPreferences(),api.codexAuthInProgress()]).then(([nextReport,nextPreferences,authInProgress])=>{setReport(nextReport);setPreferences(nextPreferences);setAuthenticating(authInProgress)}).catch(e=>setError(errorMessage(e))).finally(()=>setLoading(false))};const save=()=>{setSaving(true);setSaved(false);setError("");api.savePreferences(preferences).then(()=>setSaved(true)).catch(e=>setError(errorMessage(e))).finally(()=>setSaving(false))};const loginCodex=()=>{cancelled.current=false;setAuthenticating(true);setError("");api.loginCodex().then(status=>setReport(current=>current?{...current,codex:status}:current)).catch(e=>{if(!cancelled.current)setError(errorMessage(e))}).finally(()=>setAuthenticating(false))};const cancelCodex=()=>{cancelled.current=true;setError("");api.cancelCodexLogin().catch(e=>{cancelled.current=false;setError(errorMessage(e))})};useEffect(load,[]);useEffect(()=>{if(!authenticating)return;const timer=window.setInterval(()=>{api.codexAuthInProgress().then(active=>{if(!active){setAuthenticating(false);api.doctor().then(setReport).catch(e=>setError(errorMessage(e)))}}).catch(e=>setError(errorMessage(e)))},1000);return()=>window.clearInterval(timer)},[authenticating]);
  return <main className="settings-page"><header className="topbar"><div><button className="back-button" onClick={onBack}><ChevronLeft size={15}/>Workspace</button><h1>Settings & Doctor</h1></div><button className="secondary-button" onClick={load} disabled={loading}><RefreshCw size={14} className={loading?"spin":""}/> Run diagnostics</button></header>
    <div className="settings-content"><section><span className="eyebrow">AGENTS</span><h2>Local coding agents</h2><p className="section-copy">Duet delegates to the official CLIs on this Mac. Codex sign-in opens the official ChatGPT browser flow; credentials remain managed by Codex and are never stored by Duet.</p><div className="doctor-grid"><ToolCard name="Claude Code" initials="CL" status={report?.claude} loading={loading}/><ToolCard name="OpenAI Codex" initials="CX" status={report?.codex} loading={loading} authenticating={authenticating} onLogin={loginCodex} onCancel={cancelCodex}/></div></section>
      <section><span className="eyebrow">SYSTEM</span><h2>Runtime diagnostics</h2><div className="system-list"><SystemRow icon={GitBranch} label="Git" value={report?.git.version||"Checking…"} ok={report?.git.installed}/><SystemRow icon={Database} label="Local database" value={report?.databaseHealthy?"SQLite is healthy":"Database check failed"} ok={report?.databaseHealthy}/><SystemRow icon={HardDrive} label="Application data" value={report?.appDataWritable?"Writable":"Not writable"} ok={report?.appDataWritable}/><SystemRow icon={Command} label="Platform" value={report?.os||"Checking…"} ok={!!report}/></div></section>
      <section><span className="eyebrow">DEFAULTS</span><h2>Workspace handoff</h2><p className="section-copy">Choose where Duet opens registered projects and isolated run worktrees.</p><div className="preference-row"><label><span>Preferred editor</span><select aria-label="Preferred editor" value={preferences.editor} onChange={event=>{setSaved(false);setPreferences(value=>({...value,editor:event.target.value as AppPreferences["editor"]}))}}><option value="auto">Auto-detect</option><option value="cursor">Cursor</option><option value="vscode">Visual Studio Code</option><option value="zed">Zed</option><option value="terminal">Terminal</option><option value="finder">Finder</option></select></label><label><span>Default repair rounds</span><select aria-label="Default repair rounds" value={preferences.maxRepairs} onChange={event=>{setSaved(false);setPreferences(value=>({...value,maxRepairs:Number(event.target.value)}))}}>{[1,2,3,4,5].map(value=><option key={value}>{value}</option>)}</select></label><button className="primary-button compact" onClick={save} disabled={saving}>{saving?"Saving…":saved?"Saved":"Save defaults"}</button></div></section>
      <section className="privacy-card"><ShieldCheck/><div><h3>Local-first by design</h3><p>Duet sends no source code, prompts, logs, or agent output to a Duet cloud service. Network behavior belongs only to the official Claude and Codex CLIs you run.</p></div></section>
      {error&&<div className="error-banner" role="alert" aria-live="assertive"><CircleHelp size={16}/>{error}</div>}
    </div></main>}

function ToolCard({name,initials,status,loading,authenticating=false,onLogin,onCancel}:{name:string;initials:string;status?:ToolStatus;loading:boolean;authenticating?:boolean;onLogin?:()=>void;onCancel?:()=>void}){return <article className="tool-card"><div className={`tool-logo ${initials.toLowerCase()}`}>{initials}</div><div className="tool-info"><header><h3>{name}</h3>{loading?<span className="skeleton short"/>:<span className={`availability ${status?.installed?"ok":"bad"}`}>{status?.installed?<><Check size={12}/>Installed</>:<><X size={12}/>Missing</>}</span>}</header><dl><div><dt>Path</dt><dd>{status?.path||"Not detected"}</dd></div><div><dt>Version</dt><dd>{status?.version||"—"}</dd></div><div><dt>Authentication</dt><dd>{status?.authenticated===true?<span className="good"><KeyRound size={12}/>Authenticated</span>:status?.authenticated===false?<span className="warn">Login required or not detectable</span>:"Not detectable"}</dd></div></dl><p>{status?.detail}</p>{authenticating&&<span className="agent-login-status" role="status">Complete sign-in in your browser.</span>}{onLogin&&<div className="agent-login-actions"><button className="agent-login-button" onClick={onLogin} disabled={loading||authenticating||!status?.installed}><LogIn size={12}/>{authenticating?"Sign-in in progress":status?.authenticated?"Sign in again":"Sign in with ChatGPT"}</button>{authenticating&&onCancel&&<button className="agent-login-cancel" onClick={onCancel}><X size={12}/>Cancel</button>}</div>}</div></article>}
function SystemRow({icon:Icon,label,value,ok}:{icon:typeof GitBranch;label:string;value:string;ok?:boolean}){return <div><span className="system-icon"><Icon size={16}/></span><strong>{label}</strong><code>{value}</code><span className={`check-dot ${ok?"ok":""}`}>{ok&&<Check size={11}/>}</span></div>}
