import { listen } from "@tauri-apps/api/event";
import { confirm, message, open } from "@tauri-apps/plugin-dialog";
import { isPermissionGranted, requestPermission, sendNotification } from "@tauri-apps/plugin-notification";
import { FolderGit2, Plus, ShieldCheck } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { Sidebar } from "./components/Sidebar";
import { TaskComposer } from "./components/TaskComposer";
import { RunWorkspace } from "./components/RunWorkspace";
import { Settings } from "./components/Settings";
import { api, errorMessage, isTauriRuntime } from "./lib/api";
import type { LiveLog, Project, RunDetail, RunEvent, RunSummary, StartRunRequest } from "./types";

export default function App(){
  const [projects,setProjects]=useState<Project[]>([]);const [runs,setRuns]=useState<RunSummary[]>([]);const [selectedProject,setSelectedProject]=useState<string>();const [selectedRun,setSelectedRun]=useState<string>();const [detail,setDetail]=useState<RunDetail>();const [diff,setDiff]=useState("");const [logs,setLogs]=useState<Record<string,LiveLog[]>>({});const [screen,setScreen]=useState<"workspace"|"settings">("workspace");const [error,setError]=useState("");const [busy,setBusy]=useState("");
  const loadSequence=useRef(0);const refreshSequence=useRef(0);const refreshTimer=useRef<number|undefined>(undefined);const dataTimer=useRef<number|undefined>(undefined);const selectedRunRef=useRef<string|undefined>(undefined);
  const refresh=useCallback(async()=>{const sequence=++refreshSequence.current;try{const [p,r]=await Promise.all([api.listProjects(),api.listRuns()]);if(sequence===refreshSequence.current){setProjects(p);setRuns(r);setSelectedProject(current=>current??p[0]?.id)}}catch(e){if(sequence===refreshSequence.current)setError(errorMessage(e))}},[]);
  const loadRun=useCallback(async(id:string)=>{if(typeof id!=="string"||!id.trim())return;const sequence=++loadSequence.current;try{const [d,patch]=await Promise.all([api.getRun(id),api.getDiff(id).catch(()=>"")]);if(sequence===loadSequence.current){setDetail(d);setDiff(patch)}}catch(e){if(sequence===loadSequence.current)setError(errorMessage(e))}},[]);
  const scheduleRunLoad=useCallback((id:string)=>{window.clearTimeout(refreshTimer.current);refreshTimer.current=window.setTimeout(()=>loadRun(id),120)},[loadRun]);
  const scheduleDataRefresh=useCallback(()=>{window.clearTimeout(dataTimer.current);dataTimer.current=window.setTimeout(refresh,150)},[refresh]);
  useEffect(()=>{refresh()},[refresh]); useEffect(()=>{selectedRunRef.current=selectedRun;if(selectedRun)loadRun(selectedRun)},[selectedRun,loadRun]);
  useEffect(()=>{if(!isTauriRuntime)return;let disposed=false;const off=listen<RunEvent>("duet://run-event",async({payload})=>{if(disposed||typeof payload.runId!=="string"||!payload.runId)return;if(payload.type==="agentOutput"){setLogs(v=>({...v,[payload.runId]:[...(v[payload.runId]||[]).slice(-499),{text:`[${payload.stage}] ${payload.line}`,receivedAt:new Date().toISOString()}]}));return}if(payload.type==="stageCompleted"||["runCompleted","runFailed","runCancelled"].includes(payload.type))setLogs(v=>({...v,[payload.runId]:[]}));if(payload.runId===selectedRun)scheduleRunLoad(payload.runId);scheduleDataRefresh();if(["runCompleted","runFailed","runCancelled"].includes(payload.type))notify(payload.type==="runCompleted"?"Duet completed your task.":"Duet needs your attention.")}).catch(e=>{if(!disposed)setError(errorMessage(e));return undefined});return()=>{disposed=true;window.clearTimeout(refreshTimer.current);window.clearTimeout(dataTimer.current);void off.then(fn=>fn?.())}},[selectedRun,scheduleRunLoad,scheduleDataRefresh]);
  const addProject=async()=>{try{const path=await open({directory:true,multiple:false,title:"Choose a Git repository"});if(typeof path!=="string")return;setBusy("project");const project=await api.addProject(path);await refresh();setSelectedProject(project.id);setSelectedRun(undefined);setScreen("workspace")}catch(e){setError(errorMessage(e))}finally{setBusy("")}};
  const startRun=async(request:StartRunRequest)=>{try{setBusy("run");setDetail(undefined);setDiff("");const id=await api.startRun(request);setSelectedRun(id);await refresh();await loadRun(id)}catch(e){setError(errorMessage(e))}finally{setBusy("")}};
  const apply=async()=>{const runId=selectedRun;if(!runId||!await confirm("Apply this run's patch to the original repository? Duet will abort if the target changed or is dirty.",{title:"Apply Duet changes",kind:"warning"}))return;try{setBusy("apply");await api.applyChanges(runId);await message("Changes were applied to the original working tree. Nothing was committed or pushed.",{title:"Duet changes applied",kind:"info"})}catch(e){setError(errorMessage(e))}finally{await refresh();if(selectedRunRef.current===runId)await loadRun(runId);setBusy("")}};
  const discard=async()=>{const runId=selectedRun;if(!runId||!await confirm("Discard this Duet worktree and its temporary branch? This cannot be undone.",{title:"Discard Duet worktree",kind:"warning"}))return;try{setBusy("discard");await api.discardRun(runId)}catch(e){setError(errorMessage(e))}finally{await refresh();if(selectedRunRef.current===runId)await loadRun(runId);setBusy("")}};
  const openRunEditor=async()=>{const runId=selectedRun;if(!runId)return;try{setBusy("editor");await api.openRunInEditor(runId)}catch(e){setError(errorMessage(e))}finally{setBusy("")}};
  const revealRun=async()=>{const runId=selectedRun;if(!runId)return;try{setBusy("reveal");await api.revealRun(runId)}catch(e){setError(errorMessage(e))}finally{setBusy("")}};
  const project=projects.find(p=>p.id===selectedProject);
  return <div className="app-shell"><Sidebar projects={projects} runs={runs} selectedProject={selectedProject} selectedRun={selectedRun} onProject={id=>{setDetail(undefined);setDiff("");setSelectedProject(id);setSelectedRun(undefined);setScreen("workspace")}} onRun={id=>{setDetail(undefined);setDiff("");setSelectedRun(id);setSelectedProject(runs.find(r=>r.id===id)?.projectId);setScreen("workspace")}} onAdd={addProject} onSettings={()=>setScreen("settings")}/>
    <div className="main-shell">{screen==="settings"?<Settings onBack={()=>setScreen("workspace")}/>:selectedRun?(detail?.id===selectedRun?<RunWorkspace run={detail} diff={diff} liveLogs={logs[selectedRun]||[]} onStop={()=>api.cancelRun(selectedRun).catch(e=>setError(errorMessage(e)))} onApply={apply} onDiscard={discard} onOpenEditor={openRunEditor} onReveal={revealRun} busyAction={busy}/>:<RunLoading/>):project?<TaskComposer project={project} onRun={startRun} onError={message=>setError(message)} busy={busy==="run"}/>:<Welcome onAdd={addProject} busy={busy==="project"}/>}</div>
    {error&&<div className="toast error" role="alert" aria-live="assertive"><button aria-label="Dismiss error" onClick={()=>setError("")}>×</button><strong>Duet couldn’t continue</strong><span>{error}</span></div>}
  </div>
}

function Welcome({onAdd,busy}:{onAdd:()=>void;busy:boolean}){return <main className="welcome"><div className="welcome-mark"><span>D</span></div><span className="eyebrow">LOCAL AI ENGINEERING</span><h1>Two agents. One verified result.</h1><p>Connect a Git repository to let Codex architect and review while Claude builds and repairs—entirely inside an isolated worktree.</p><button className="primary-button" onClick={onAdd} disabled={busy}><Plus size={15}/>{busy?"Inspecting…":"Add your first project"}</button><div className="welcome-points"><span><FolderGit2/>Worktree isolated</span><span><ShieldCheck/>Objectively verified</span></div></main>}
function RunLoading(){return <main className="run-loading" aria-busy="true"><span className="skeleton wide"/><span className="skeleton medium"/><div className="skeleton-card"/></main>}
async function notify(body:string){try{let granted=await isPermissionGranted();if(!granted)granted=(await requestPermission())==="granted";if(granted)sendNotification({title:"Duet",body})}catch{/* Notifications are optional. */}}
